spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/uid_generator?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 初始连接数
    initialSize: 5
    # 最小连接数
    minIdle: 5
    # 最大连接池数量
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 用来检测连接是否有效的sql
    validationQuery: SELECT 1 FROM DUAL
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  tomcat:
    uri-encoding: UTF-8

mybatis-plus:
  check-config-location: true  #启动时检查MyBatis XML文件的存在
  executor-type: reuse #复用预处理语句
  configuration:
    map-underscore-to-camel-case: true #开启自动驼峰命名规则
    auto-mapping-unknown-column-behavior: warning #自动映射时未知列或未知属性处理策略，以日志打印警告信息
    cache-enabled: true #全局开启所有映射器已经配置的任何缓存
    call-setters-on-nulls: false #指定当结果集中值为null时不调用映射对象的Setter
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql
  global-config:
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mapper/**/*.xml

